apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.firstAppName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.firstAppName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.firstAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.firstAppName }}
    spec:
      containers:
      - name: {{ .Values.firstAppName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.firstAppName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.firstAppName }}
  ports:
    - protocol: TCP
      port: 80
