apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.secondAppName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.secondAppName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.secondAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.secondAppName }}
    spec:
      containers:
      - name: {{ .Values.secondAppName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.secondAppName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.secondAppName }}
  ports:
    - protocol: TCP
      port: 80
